[mypy]
python_version = 3.11
ignore_missing_imports = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
check_untyped_defs = false

[mypy-kubernetes.*]
ignore_missing_imports = true

[mypy-prometheus_client.*]
ignore_missing_imports = true

[mypy-opentelemetry.*]
ignore_missing_imports = true

[mypy-sqlalchemy.*]
ignore_missing_imports = true

[mypy-aiosmtplib.*]
ignore_missing_imports = true

[mypy-aiokafka.*]
ignore_missing_imports = true
